pool:
    vmImage: 'Ubuntu-16.04'
    demands: npm

steps:
    - task: NodeTool@0
      displayName: 'Use Node 8.x'
      inputs:
          versionSpec: 8.x
          checkLatest: true

    - task: Npm@1
      displayName: 'npm install'
      inputs:
          verbose: false
